const express=require('express');
const app=express();
const PORT=process.env.PORT||3000;
const {assets}=require('./src/store');
const operationsDb=require('./src/persistent-store');
app.use(express.json({limit:'60mb'}));

const htmlEsc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

app.get('/api/diagnostics/prestart-defects',(req,res)=>{
  try{
    const prestarts=operationsDb.listPrestarts();
    const defects=operationsDb.listDefects();
    const latest=[...prestarts].sort((a,b)=>new Date(b.completedAt||0)-new Date(a.completedAt||0))[0]||null;
    if(!latest)return res.json({ok:false,storeFile:operationsDb.FILE,prestartCount:0,defectCount:defects.length,message:'No persisted pre-starts found on this running instance.'});
    const failed=(latest.results||[]).filter(x=>String(x.value||'').trim().toLowerCase()==='fail');
    const linked=defects.filter(d=>String(d.prestartId)===String(latest.id));
    const missing=failed.filter(f=>!linked.some(d=>String(d.prestartItemId)===String(f.itemId)));
    res.set('Cache-Control','no-store');
    res.json({ok:missing.length===0&&linked.length>=failed.length,storeFile:operationsDb.FILE,prestartCount:prestarts.length,defectCount:defects.length,latestPrestart:{id:latest.id,completedAt:latest.completedAt,assetId:latest.assetId,assetName:latest.assetName,rego:latest.rego,status:latest.status,failedCountStored:latest.failedCount,failedItems:failed.map(x=>({itemId:x.itemId,label:x.label,value:x.value}))},linkedDefects:linked.map(d=>({id:d.id,prestartItemId:d.prestartItemId,defect:d.defect,status:d.status,priority:d.priority})),missingDefects:missing.map(x=>({itemId:x.itemId,label:x.label})),diagnosis:failed.length===0?'Latest persisted pre-start contains no FAIL values.':missing.length?'FAIL values were persisted but matching defect records are missing.':'Latest failed items have matching persisted defect records.'});
  }catch(e){res.status(500).json({ok:false,error:e.message,storeFile:operationsDb.FILE})}
});

app.use((req,res,next)=>{
  const originalSend=res.send.bind(res);
  res.send=(body)=>{
    if(typeof body==='string'&&req.path==='/prestarts'){
      body=body.replace("&z=17&output=embed\"></iframe>'}}function captureLocation","&z=17&output=embed\"></iframe>'}}}function captureLocation");
      const available=assets.filter(a=>!['Retired','Decommissioned','Sold'].includes(a.status));
      const options=available.map(a=>`<option value="${htmlEsc(a.id)}">${htmlEsc(a.rego||a.id)} · ${htmlEsc(a.name)} · ${htmlEsc(a.type)}</option>`).join('');
      body=body.replace('<select id="primary" class="bigSelect"><option value="">Select primary asset...</option></select>',`<select id="primary" class="bigSelect"><option value="">Select primary asset...</option>${options}</select>`);
      const selectorSafety=`<script>(()=>{const p=document.getElementById('primary'),b=document.getElementById('beginBtn'),preview=document.getElementById('primaryPreview');if(!p)return;const assets=${JSON.stringify(available).replace(/</g,'\\u003c')};const sync=()=>{const a=assets.find(x=>String(x.id)===String(p.value));if(b)b.disabled=!a;if(preview)preview.innerHTML=a?'<div class="assetPreview"><b>'+a.name+'</b><div class="sub">'+(a.type||'')+' · '+(a.rego||a.id)+'</div></div>':''};p.addEventListener('change',sync);sync()})();</script>`;
      body=body.replace('</body>',selectorSafety+'</body>');
      const driverLatch=`<script>(()=>{const primary=document.getElementById('primary'),begin=document.getElementById('beginBtn');if(!primary||!begin||document.getElementById('prestartEmployee'))return;const card=primary.closest('.stepCard');if(!card)return;const wrap=document.createElement('div');wrap.style.cssText='margin-bottom:16px;padding:13px;border:1px solid #dce7f5;background:#f8fbff;border-radius:10px';wrap.innerHTML='<div class="field"><label>Driver / Employee <span class="req">*</span></label><select id="prestartEmployee" class="bigSelect"><option value="">Loading employees...</option></select><div id="prestartEmployeeHint" class="sub" style="margin-top:6px">The selected employee will be latched to the primary asset when this pre-start is submitted.</div></div>';const heading=card.querySelector('h3');card.insertBefore(wrap,heading);const select=document.getElementById('prestartEmployee'),hint=document.getElementById('prestartEmployeeHint');let employeeList=[];const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function loadEmployees(){try{const r=await fetch('/api/employees',{cache:'no-store'}),d=await r.json();employeeList=Array.isArray(d)?d:[];if(!employeeList.length){select.innerHTML='<option value="">No employees available</option>';select.disabled=true;hint.innerHTML='No employee records are available. <a href="/employees">Add an employee</a> to enable automatic driver latching.';return}select.innerHTML='<option value="">Select driver / employee...</option>'+employeeList.map(e=>'<option value="'+esc(e.id)+'">'+esc([e.firstName,e.lastName].filter(Boolean).join(' '))+(e.employeeAccess?' · '+esc(e.employeeAccess):'')+'</option>').join('')}catch(e){select.innerHTML='<option value="">Unable to load employees</option>';hint.textContent='Employee list could not be loaded. The pre-start can still be completed without a driver assignment.'}}begin.addEventListener('click',e=>{if(employeeList.length&&!select.value){e.preventDefault();e.stopImmediatePropagation();select.focus();alert('Select the driver / employee completing this pre-start.')}},true);const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init)=>{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.includes('/api/prestarts')&&init&&String(init.method||'').toUpperCase()==='POST'&&init.body){try{const payload=JSON.parse(init.body);if(Array.isArray(payload.records))payload.records=payload.records.map((r,i)=>({...r,isPrimary:i===0}));if(select.value){const e=employeeList.find(x=>String(x.id)===String(select.value));payload.employeeId=select.value;if(e)payload.inspector=[e.firstName,e.lastName].filter(Boolean).join(' ')}init={...init,body:JSON.stringify(payload)}}catch{}}return nativeFetch(input,init)};loadEmployees()})();</script>`;
      body=body.replace('</body>',driverLatch+'</body>');
    }
    if(typeof body==='string'&&body.includes('<span class="navlabel">WORKFORCE</span>')){
      if(!body.includes('href="/vehicle-defects"')){const active=req.path==='/vehicle-defects'?'on':'';const defectsLink=`<a class="${active}" href="/vehicle-defects" title="Vehicle Defects"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5"/><circle cx="12" cy="17" r=".8"/></svg></span><span class="navtext">Vehicle Defects</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',defectsLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/incident-register"')){const active=req.path.startsWith('/incident-register')?'on':'';const incidentLink=`<a class="${active}" href="/incident-register" title="Incident Register"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h5M8 16h3"/><path d="M16 13v5M13.5 15.5h5"/></svg></span><span class="navtext">Incident Register</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',incidentLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/service"')){const active=req.path==='/service'?'on':'';const serviceLink=`<a class="${active}" href="/service" title="Service Schedule"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M5 7h14v12H5z"/><path d="M8 4v6M16 4v6M8 14h3M13 14h3"/></svg></span><span class="navtext">Service Schedule</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',serviceLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/service-history"')){const active=req.path==='/service-history'?'on':'';const serviceHistoryLink=`<a class="${active}" href="/service-history" title="Service History"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span><span class="navtext">Service History</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',serviceHistoryLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/prestart-history"')){const active=req.path==='/prestart-history'?'on':'';const historyLink=`<a class="${active}" href="/prestart-history" title="Pre-Start History"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span><span class="navtext">Pre-Start History</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',historyLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/gps"')){const active=req.path==='/gps'?'on':'';const gpsLink=`<a class="${active}" href="/gps" title="Live GPS"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg></span><span class="navtext">Live GPS</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',gpsLink+'<span class="navlabel">WORKFORCE</span>')}
      if(!body.includes('href="/gps-integration"')){const active=req.path==='/gps-integration'?'on':'';const cfgLink=`<a class="${active}" href="/gps-integration" title="GPS Integration"><span class="navicon"><svg viewBox="0 0 24 24"><path d="M8 12h8M12 8v8"/><circle cx="12" cy="12" r="8"/></svg></span><span class="navtext">GPS Integration</span><span class="navchev">›</span></a>`;body=body.replace('<span class="navlabel">WORKFORCE</span>',cfgLink+'<span class="navlabel">WORKFORCE</span>')}
    }
    if(typeof body==='string'&&req.path==='/prestarts'&&req.query.asset&&body.includes('id="primary"')){const assetId=JSON.stringify(String(req.query.asset));const preselect=`<script>(()=>{const assetId=${assetId};const apply=()=>{const el=document.getElementById('primary');if(!el)return false;const match=[...el.options].some(o=>o.value===assetId);if(!match)return true;el.value=assetId;el.dispatchEvent(new Event('change',{bubbles:true}));const preview=document.getElementById('primaryPreview');if(preview)preview.scrollIntoView({behavior:'smooth',block:'center'});return true};if(!apply()){let tries=0;const timer=setInterval(()=>{tries++;if(apply()||tries>20)clearInterval(timer)},100)}})();</script>`;body=body.replace('</body>',preselect+'</body>')}
    if(typeof body==='string'&&req.path==='/assets'){
      const currentDriverView=`<script>(()=>{let selectedAssetId='';const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));document.addEventListener('click',e=>{const btn=e.target.closest&&e.target.closest('[data-view]');if(!btn)return;selectedAssetId=btn.dataset.view;setTimeout(showDriver,70)},true);async function showDriver(){if(!selectedAssetId)return;const body=document.getElementById('viewBody');if(!body)return;let hero=body.querySelector('.assetHero');if(!hero){setTimeout(showDriver,60);return}body.querySelectorAll('.currentDriverCard').forEach(x=>x.remove());try{const r=await fetch('/api/assets/'+encodeURIComponent(selectedAssetId),{cache:'no-store'}),a=await r.json();if(!r.ok)throw new Error(a.error||'Unable to load driver');const assigned=!!a.currentDriverEmployeeId;const when=a.driverLatchedAt?new Date(a.driverLatchedAt).toLocaleString('en-AU'):'—';const card=document.createElement('section');card.className='currentDriverCard';card.style.cssText='margin-top:14px;border:1px solid '+(assigned?'#b9e4ca':'#e5eaf0')+';background:'+(assigned?'#f4fbf7':'#fafbfd')+';border-radius:12px;padding:14px 16px;display:flex;align-items:center;gap:13px';card.innerHTML='<div style="width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:'+(assigned?'#daf4e4':'#edf1f5')+';color:'+(assigned?'#17884c':'#7c8898')+';flex:0 0 42px"><svg viewBox="0 0 24 24" style="width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round"><circle cx="12" cy="8" r="3.5"/><path d="M5.5 20a6.5 6.5 0 0 1 13 0"/></svg></div><div style="min-width:0;flex:1"><div style="font-size:10px;font-weight:850;letter-spacing:.8px;text-transform:uppercase;color:#7b8797;margin-bottom:4px">Current Driver</div><div style="font-size:16px;font-weight:800;color:#263244">'+esc(assigned?a.currentDriverName:'No driver currently assigned')+'</div>'+(assigned?'<div class="sub" style="margin-top:4px">'+esc([a.currentDriverPhone,a.currentDriverEmail].filter(Boolean).join(' · '))+'</div><div class="sub" style="margin-top:3px">Latched by pre-start '+esc(a.driverPrestartId||'')+' · '+esc(when)+'</div>':'<div class="sub" style="margin-top:4px">The next employee who completes a pre-start on this primary asset will be shown here.</div>')+'</div>';hero.insertAdjacentElement('afterend',card)}catch(e){console.warn('Current driver display failed',e)}}})();</script>`;
      body=body.replace('</body>',currentDriverView+'</body>');
    }
    if(typeof body==='string'&&req.path==='/gps'){
      const gpsActionIcons=`<script>(()=>{const icons={geofence:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>',share:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.5M8.2 13.2l7.6 4.5"/></svg>',integration:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.5 15.5 6 18a3.5 3.5 0 0 1-5-5l3-3a3.5 3.5 0 0 1 5 0"/><path d="M15.5 8.5 18 6a3.5 3.5 0 0 1 5 5l-3 3a3.5 3.5 0 0 1-5 0"/><path d="m8 16 8-8"/></svg>'};function iconize(el,label,svg){if(!el||el.dataset.topIconized==='1')return;el.dataset.topIconized='1';el.innerHTML=svg;el.title=label;el.setAttribute('aria-label',label);el.style.width='42px';el.style.height='42px';el.style.padding='0';el.style.display='inline-grid';el.style.placeItems='center';el.style.flex='0 0 42px';el.style.borderRadius='10px';el.style.lineHeight='1';const s=el.querySelector('svg');if(s){s.style.width='19px';s.style.height='19px';s.style.fill='none';s.style.stroke='currentColor';s.style.strokeWidth='1.8';s.style.strokeLinecap='round';s.style.strokeLinejoin='round'}}function apply(){iconize(document.getElementById('newGeofenceBtn'),'New Geofence',icons.geofence);iconize(document.getElementById('shareLive'),'Share Live Location',icons.share);iconize(document.querySelector('.title a[href="/gps-integration"]'),'GPS Integration',icons.integration)}apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),5000)})();</script>`;
      body=body.replace('</body>',gpsActionIcons+'</body>');
    }
    return originalSend(body);
  };next();
});
app.use(require('./src/routes/assets'));
app.use(require('./src/routes/asset-qr'));
app.use(require('./src/routes/employees'));
app.use(require('./src/routes/prestart-config'));
app.use(require('./src/routes/prestart-submit'));
app.use(require('./src/routes/prestarts-mobile'));
app.use(require('./src/routes/prestart-history'));
app.use(require('./src/routes/vehicle-defects-v2'));
app.use(require('./src/routes/vehicle-defects'));
app.use(require('./src/routes/incident-management'));
app.use(require('./src/routes/incident-register'));
// Reliable server-backed service workflow must be mounted before the legacy route.
app.use(require('./src/routes/services-v2'));
app.use(require('./src/routes/services'));
app.use(require('./src/routes/gps'));
app.get('/defects',(req,res)=>res.redirect('/vehicle-defects'));
app.get('/vehicleDefects',(req,res)=>res.redirect('/vehicle-defects'));
app.get('/',(req,res)=>res.redirect('/assets'));
app.use((req,res)=>res.status(404).send('Supervisor365 page not found'));
app.listen(PORT,'0.0.0.0',()=>console.log('Supervisor365 modular master running on '+PORT));
