const express=require('express');
const router=express.Router();
const {page}=require('../layout');
const {assets,assetTypes}=require('../store');
const states=[['NSW','New South Wales (NSW)'],['VIC','Victoria (VIC)'],['QLD','Queensland (QLD)'],['SA','South Australia (SA)'],['WA','Western Australia (WA)'],['TAS','Tasmania (TAS)'],['NT','Northern Territory (NT)'],['ACT','Australian Capital Territory (ACT)'],['OTH','Other (OTH)']];
const statuses=['In Service','Maintenance','Decommissioned','Retired','Sold'];
const clean=v=>String(v??'').trim();
function sanitiseImages(v){return Array.isArray(v)?v.filter(x=>typeof x==='string'&&x.startsWith('data:image/')).slice(0,10):[]}
function applyAsset(asset,b){asset.type=clean(b.type);asset.rego=clean(b.rego).toUpperCase();asset.registrationState=clean(b.registrationState);asset.registrationExpiry=clean(b.registrationExpiry);asset.status=clean(b.status)||'In Service';asset.make=clean(b.make);asset.model=clean(b.model);asset.name=`${asset.make} ${asset.model}`.trim();asset.vin=clean(b.vin);asset.reading=Number(b.reading)||0;asset.acquisitionDate=clean(b.acquisitionDate);asset.category=clean(b.category);asset.refrigerationInspectionDate=clean(b.refrigerationInspectionDate);asset.handbrakeAlarm=!!b.handbrakeAlarm;asset.reverseCamera=!!b.reverseCamera;asset.adasVideo=!!b.adasVideo;asset.insuranceExpiry=clean(b.insuranceExpiry);asset.compliancePlateDate=clean(b.compliancePlateDate);asset.coiNumber=clean(b.coiNumber);asset.coiDueDate=clean(b.coiDueDate);asset.plantId=clean(b.plantId);asset.additionalNotes=clean(b.additionalNotes);asset.location=clean(b.location);asset.serviceDue=!!b.serviceDue;asset.images=sanitiseImages(b.images);return asset}
router.get('/api/assets',(req,res)=>res.json(assets));
router.get('/api/assets/:id',(req,res)=>{const a=assets.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Asset not found'});res.json(a)});
router.get('/api/asset-summary',(req,res)=>res.json({total:assets.length,active:assets.filter(a=>a.status==='In Service').length,serviceDue:assets.filter(a=>a.serviceDue).length,openDefects:assets.reduce((n,a)=>n+(Number(a.openDefects)||0),0)}));
router.post('/api/assets',(req,res)=>{const b=req.body||{};if(!b.type||!b.rego||!b.status||!b.make||!b.model||b.reading===''||b.reading==null)return res.status(400).json({error:'Asset type, registration, status, make, model and current odometer are required'});if(assets.some(a=>a.rego.toLowerCase()===clean(b.rego).toLowerCase()))return res.status(409).json({error:'Registration already exists'});const asset={id:'AST-'+Date.now().toString(36).toUpperCase(),openDefects:0};applyAsset(asset,b);assets.push(asset);res.status(201).json(asset)});
router.put('/api/assets/:id',(req,res)=>{const asset=assets.find(a=>a.id===req.params.id);if(!asset)return res.status(404).json({error:'Asset not found'});const b=req.body||{};if(!b.type||!b.rego||!b.status||!b.make||!b.model||b.reading===''||b.reading==null)return res.status(400).json({error:'Asset type, registration, status, make, model and current odometer are required'});if(assets.some(a=>a.id!==asset.id&&a.rego.toLowerCase()===clean(b.rego).toLowerCase()))return res.status(409).json({error:'Registration already exists'});res.json(applyAsset(asset,b))});
const stateOptions=states.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');
const statusOptions=statuses.map(x=>`<option>${x}</option>`).join('');
router.get('/assets',(req,res)=>res.send(page('assets','Assets',`
<style>.assetIconBtn{width:36px;height:36px;padding:0;border:1px solid #d9e0e8;background:#fff;border-radius:9px;display:inline-grid;place-items:center;color:#526175;cursor:pointer;transition:.15s}.assetIconBtn:hover{background:#f0f7ff;border-color:#9bc4f5;color:#1768c5;transform:translateY(-1px)}.assetIconBtn svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}</style>
<section class="title"><div><h1>Assets</h1><p>Manage vehicles, plant, machinery and equipment across your operations.</p></div><button class="primary" id="addAssetBtn">＋ Add Asset</button></section>
<section class="cards"><div class="card"><label>Total Assets</label><strong id="total"></strong></div><div class="card"><label>Active</label><strong id="active"></strong></div><div class="card"><label>Due for Service</label><strong id="serviceDue"></strong></div><div class="card"><label>Open Defects</label><strong id="openDefects"></strong></div></section>
<div class="toolbar"><input id="search" placeholder="Search assets..."><select id="typeFilter"><option value="">All Asset Types</option>${assetTypes.map(x=>`<option>${x}</option>`).join('')}</select></div>
<section class="panel"><div class="tablewrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Registration</th><th>Plant ID</th><th>Odometer</th><th>Status</th><th>Actions</th></tr></thead><tbody id="rows"></tbody></table></div></section>
<div class="modal" id="assetModal"><div class="box"><div class="modalhead"><h2 id="modalTitle">Add Asset</h2><button class="close" data-close="assetModal">×</button></div><div class="viewerbody"><div class="grid">
<div class="field"><label>Asset Type *</label><select id="fType">${assetTypes.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Registration Number *</label><input id="fRego"></div><div class="field"><label>Registration State</label><select id="fRegistrationState"><option value="">Select Registration State</option>${stateOptions}</select></div><div class="field"><label>Registration Expiry Date</label><input id="fRegistrationExpiry" type="date"></div><div class="field"><label>Asset Status *</label><select id="fStatus">${statusOptions}</select></div><div class="field"><label>Make *</label><input id="fMake" list="makeList" placeholder="Select / enter make..."><datalist id="makeList"><option>Kenworth</option><option>Volvo</option><option>Mack</option><option>Mercedes-Benz</option><option>Isuzu</option><option>Hino</option><option>CAT</option><option>Komatsu</option><option>Toyota</option><option>Ford</option><option>MaxiTRANS</option></datalist></div><div class="field"><label>Model *</label><input id="fModel"></div><div class="field"><label>VIN</label><input id="fVin"></div><div class="field"><label>Current Odometer Reading *</label><input id="fReading" type="number" min="0"></div><div class="field"><label>Acquisition Date (Optional)</label><input id="fAcquisitionDate" type="date"></div><div class="field"><label>Category (Optional)</label><input id="fCategory"></div><div class="field"><label>Refrigeration Last Inspection Date (Optional)</label><input id="fRefrigerationInspectionDate" type="date"></div><label class="toggle"><input type="checkbox" id="fHandbrakeAlarm"> Handbrake Alarm</label><label class="toggle"><input type="checkbox" id="fReverseCamera"> Reverse Camera</label><label class="toggle"><input type="checkbox" id="fAdasVideo"> ADAS 4-Way Video</label><div class="field"><label>Insurance Expiry (Optional)</label><input id="fInsuranceExpiry" type="date"></div><div class="field"><label>Compliance Plate Date (Optional)</label><input id="fCompliancePlateDate" type="date"></div><div class="field"><label>Certificate of Inspection Number (Optional)</label><input id="fCoiNumber"></div><div class="field"><label>Certificate of Inspection Due Date (Optional)</label><input id="fCoiDueDate" type="date"></div><div class="field"><label>Asset ID or Plant ID (Optional)</label><input id="fPlantId"></div><div class="field"><label>Location</label><input id="fLocation"></div><label class="toggle"><input type="checkbox" id="fServiceDue"> Due for Service</label><div class="field full"><label>Additional Notes</label><textarea id="fAdditionalNotes" rows="4"></textarea></div>
<div class="field full"><label>Asset Images</label><div class="sub" style="margin-bottom:8px">Upload up to 10 photos. Images are automatically resized for faster loading.</div><input id="fImages" type="file" accept="image/*" multiple><div id="imageCount" class="sub" style="margin-top:8px"></div><div id="imagePreview" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:10px;margin-top:10px"></div></div>
</div></div><div class="actions"><button class="secondary" data-close="assetModal">Cancel</button><button class="primary" id="saveAsset">Save Asset</button></div></div></div>
<div class="modal" id="viewModal"><div class="box"><div class="modalhead"><h2>Asset Details</h2><button class="close" data-close="viewModal">×</button></div><div class="viewerbody" id="viewBody"></div><div class="actions"><button class="secondary" data-close="viewModal">Close</button><a class="secondary" id="qrFromView" href="#">QR Code</a><button class="primary" id="editFromView">Edit Asset</button></div></div></div>
<script>(()=>{const $=id=>document.getElementById(id);let list=[],editingId=null,viewingId=null,imageDraft=[];const fields=['Type','Rego','RegistrationState','RegistrationExpiry','Status','Make','Model','Vin','Reading','AcquisitionDate','Category','RefrigerationInspectionDate','InsuranceExpiry','CompliancePlateDate','CoiNumber','CoiDueDate','PlantId','Location','AdditionalNotes'];
const eye='<svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>',edit='<svg viewBox="0 0 24 24"><path d="M4 20h4l11-11-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg>',qr='<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><path d="M14 14h3v3h-3zM19 14h2v2M14 19h2v2M18 18h3v3"/></svg>';
async function load(){list=await fetch('/api/assets').then(r=>r.json());const s=await fetch('/api/asset-summary').then(r=>r.json());$('total').textContent=s.total;$('active').textContent=s.active;$('serviceDue').textContent=s.serviceDue;$('openDefects').textContent=s.openDefects;render()}
function render(){const q=$('search').value.toLowerCase(),t=$('typeFilter').value;$('rows').innerHTML=list.filter(a=>(!t||a.type===t)&&(!q||[a.name,a.type,a.rego,a.plantId,a.vin].join(' ').toLowerCase().includes(q))).map(a=>'<tr><td><b>'+a.name+'</b><div class="sub">'+(a.category||'')+(a.images&&a.images.length?' · '+a.images.length+' photo'+(a.images.length===1?'':'s'):'')+'</div></td><td>'+a.type+'</td><td>'+a.rego+'<div class="sub">'+(a.registrationState||'')+'</div></td><td>'+(a.plantId||'—')+'</td><td>'+Number(a.reading||0).toLocaleString('en-AU')+'</td><td><span class="pill '+(a.status==='In Service'?'ok':'due')+'">'+a.status+'</span></td><td><div class="actionlinks"><button class="assetIconBtn" data-view="'+a.id+'" title="View asset" aria-label="View asset">'+eye+'</button><button class="assetIconBtn" data-edit="'+a.id+'" title="Edit asset" aria-label="Edit asset">'+edit+'</button><a class="assetIconBtn" href="/assets/'+encodeURIComponent(a.id)+'/qr" title="Asset QR code" aria-label="Asset QR code">'+qr+'</a></div></td></tr>').join('');$('rows').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewAsset(b.dataset.view));$('rows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function renderImages(){$('imageCount').textContent=imageDraft.length+' of 10 images';$('imagePreview').innerHTML=imageDraft.map((src,i)=>'<div style="position:relative;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;background:#fff"><img src="'+src+'" style="width:100%;height:100px;object-fit:cover;display:block"><button type="button" data-remove-image="'+i+'" style="position:absolute;right:5px;top:5px;width:26px;height:26px;border:0;border-radius:50%;background:#111827dd;color:#fff;cursor:pointer">×</button></div>').join('');$('imagePreview').querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{imageDraft.splice(Number(b.dataset.removeImage),1);renderImages()})}
function reset(){editingId=null;$('modalTitle').textContent='Add Asset';fields.forEach(n=>{const e=$('f'+n);if(e)e.value=''});$('fType').selectedIndex=0;$('fStatus').value='In Service';['HandbrakeAlarm','ReverseCamera','AdasVideo','ServiceDue'].forEach(n=>$('f'+n).checked=false);$('fImages').value='';imageDraft=[];renderImages()}
function fill(a){$('fType').value=a.type||'';$('fRego').value=a.rego||'';$('fRegistrationState').value=a.registrationState||'';$('fRegistrationExpiry').value=a.registrationExpiry||'';$('fStatus').value=a.status||'In Service';$('fMake').value=a.make||'';$('fModel').value=a.model||'';$('fVin').value=a.vin||'';$('fReading').value=a.reading??'';$('fAcquisitionDate').value=a.acquisitionDate||'';$('fCategory').value=a.category||'';$('fRefrigerationInspectionDate').value=a.refrigerationInspectionDate||'';$('fHandbrakeAlarm').checked=!!a.handbrakeAlarm;$('fReverseCamera').checked=!!a.reverseCamera;$('fAdasVideo').checked=!!a.adasVideo;$('fInsuranceExpiry').value=a.insuranceExpiry||'';$('fCompliancePlateDate').value=a.compliancePlateDate||'';$('fCoiNumber').value=a.coiNumber||'';$('fCoiDueDate').value=a.coiDueDate||'';$('fPlantId').value=a.plantId||'';$('fLocation').value=a.location||'';$('fServiceDue').checked=!!a.serviceDue;$('fAdditionalNotes').value=a.additionalNotes||'';$('fImages').value='';imageDraft=[...(a.images||[])];renderImages()}
function openEdit(id){const a=list.find(x=>x.id===id);if(!a)return;editingId=id;$('modalTitle').textContent='Edit Asset';fill(a);$('assetModal').classList.add('open')}
function gallery(a){return a.images&&a.images.length?'<h3 style="margin-top:24px">Asset Images</h3><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px">'+a.images.map(src=>'<a href="'+src+'" target="_blank"><img src="'+src+'" style="width:100%;height:150px;object-fit:cover;border-radius:10px;border:1px solid #e5e7eb"></a>').join('')+'</div>':''}
function viewAsset(id){const a=list.find(x=>x.id===id);if(!a)return;viewingId=id;$('qrFromView').href='/assets/'+encodeURIComponent(id)+'/qr';const d=(label,v)=>'<div class="detail"><small>'+label+'</small><b>'+(v||'—')+'</b></div>';$('viewBody').innerHTML='<div class="detailgrid">'+d('Asset',a.name)+d('Asset Type',a.type)+d('Registration',a.rego)+d('Registration State',a.registrationState)+d('Registration Expiry',a.registrationExpiry)+d('Status',a.status)+d('Make',a.make)+d('Model',a.model)+d('VIN',a.vin)+d('Current Odometer',Number(a.reading||0).toLocaleString('en-AU'))+d('Acquisition Date',a.acquisitionDate)+d('Category',a.category)+d('Refrigeration Inspection',a.refrigerationInspectionDate)+d('Handbrake Alarm',a.handbrakeAlarm?'Yes':'No')+d('Reverse Camera',a.reverseCamera?'Yes':'No')+d('ADAS 4-Way Video',a.adasVideo?'Yes':'No')+d('Insurance Expiry',a.insuranceExpiry)+d('Compliance Plate Date',a.compliancePlateDate)+d('COI Number',a.coiNumber)+d('COI Due Date',a.coiDueDate)+d('Asset / Plant ID',a.plantId)+d('Location',a.location)+'</div>'+gallery(a)+'<h3>Additional Notes</h3><p>'+(a.additionalNotes||'—')+'</p>';$('viewModal').classList.add('open')}
function compress(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=e=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',0.82))};img.src=e.target.result};reader.readAsDataURL(file)})}
$('fImages').onchange=async e=>{const files=[...e.target.files];for(const f of files){if(imageDraft.length>=10)break;if(!f.type.startsWith('image/'))continue;try{imageDraft.push(await compress(f))}catch{}}renderImages();e.target.value=''};
$('addAssetBtn').onclick=()=>{reset();$('assetModal').classList.add('open')};$('editFromView').onclick=()=>{$('viewModal').classList.remove('open');openEdit(viewingId)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$((b.dataset.close)).classList.remove('open'));$('search').oninput=render;$('typeFilter').onchange=render;
$('saveAsset').onclick=async()=>{const body={type:$('fType').value,rego:$('fRego').value,registrationState:$('fRegistrationState').value,registrationExpiry:$('fRegistrationExpiry').value,status:$('fStatus').value,make:$('fMake').value,model:$('fModel').value,vin:$('fVin').value,reading:$('fReading').value,acquisitionDate:$('fAcquisitionDate').value,category:$('fCategory').value,refrigerationInspectionDate:$('fRefrigerationInspectionDate').value,handbrakeAlarm:$('fHandbrakeAlarm').checked,reverseCamera:$('fReverseCamera').checked,adasVideo:$('fAdasVideo').checked,insuranceExpiry:$('fInsuranceExpiry').value,compliancePlateDate:$('fCompliancePlateDate').value,coiNumber:$('fCoiNumber').value,coiDueDate:$('fCoiDueDate').value,plantId:$('fPlantId').value,location:$('fLocation').value,serviceDue:$('fServiceDue').checked,additionalNotes:$('fAdditionalNotes').value,images:imageDraft};const r=await fetch(editingId?'/api/assets/'+editingId:'/api/assets',{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error||'Unable to save asset');$('assetModal').classList.remove('open');await load()};load()})();</script>`)));
module.exports=router;
