const express=require('express');
const router=express.Router();
const {page}=require('../layout');
const {assets,assetTypes}=require('../store');
const states=[['NSW','New South Wales (NSW)'],['VIC','Victoria (VIC)'],['QLD','Queensland (QLD)'],['SA','South Australia (SA)'],['WA','Western Australia (WA)'],['TAS','Tasmania (TAS)'],['NT','Northern Territory (NT)'],['ACT','Australian Capital Territory (ACT)'],['OTH','Other (OTH)']];
const statuses=['In Service','Maintenance','Decommissioned','Retired','Sold'];
const clean=v=>String(v??'').trim();
function applyAsset(asset,b){
  asset.type=clean(b.type); asset.rego=clean(b.rego).toUpperCase(); asset.registrationState=clean(b.registrationState); asset.registrationExpiry=clean(b.registrationExpiry);
  asset.status=clean(b.status)||'In Service'; asset.make=clean(b.make); asset.model=clean(b.model); asset.name=`${asset.make} ${asset.model}`.trim(); asset.vin=clean(b.vin);
  asset.reading=Number(b.reading)||0; asset.acquisitionDate=clean(b.acquisitionDate); asset.category=clean(b.category); asset.refrigerationInspectionDate=clean(b.refrigerationInspectionDate);
  asset.handbrakeAlarm=!!b.handbrakeAlarm; asset.reverseCamera=!!b.reverseCamera; asset.adasVideo=!!b.adasVideo; asset.insuranceExpiry=clean(b.insuranceExpiry);
  asset.compliancePlateDate=clean(b.compliancePlateDate); asset.coiNumber=clean(b.coiNumber); asset.coiDueDate=clean(b.coiDueDate); asset.plantId=clean(b.plantId);
  asset.additionalNotes=clean(b.additionalNotes); asset.location=clean(b.location); asset.serviceDue=!!b.serviceDue; return asset;
}
router.get('/api/assets',(req,res)=>res.json(assets));
router.get('/api/assets/:id',(req,res)=>{const a=assets.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Asset not found'});res.json(a)});
router.get('/api/asset-summary',(req,res)=>res.json({total:assets.length,active:assets.filter(a=>a.status==='In Service').length,serviceDue:assets.filter(a=>a.serviceDue).length,openDefects:assets.reduce((n,a)=>n+(Number(a.openDefects)||0),0)}));
router.post('/api/assets',(req,res)=>{const b=req.body||{};if(!b.type||!b.rego||!b.status||!b.make||!b.model||b.reading===''||b.reading==null)return res.status(400).json({error:'Asset type, registration, status, make, model and current odometer are required'});if(assets.some(a=>a.rego.toLowerCase()===clean(b.rego).toLowerCase()))return res.status(409).json({error:'Registration already exists'});const asset={id:'AST-'+Date.now().toString(36).toUpperCase(),openDefects:0};applyAsset(asset,b);assets.push(asset);res.status(201).json(asset)});
router.put('/api/assets/:id',(req,res)=>{const asset=assets.find(a=>a.id===req.params.id);if(!asset)return res.status(404).json({error:'Asset not found'});const b=req.body||{};if(!b.type||!b.rego||!b.status||!b.make||!b.model||b.reading===''||b.reading==null)return res.status(400).json({error:'Asset type, registration, status, make, model and current odometer are required'});if(assets.some(a=>a.id!==asset.id&&a.rego.toLowerCase()===clean(b.rego).toLowerCase()))return res.status(409).json({error:'Registration already exists'});res.json(applyAsset(asset,b))});

const stateOptions=states.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');
const statusOptions=statuses.map(x=>`<option>${x}</option>`).join('');
router.get('/assets',(req,res)=>res.send(page('assets','Assets',`
<section class="title"><div><h1>Assets</h1><p>Manage vehicles, plant, machinery and equipment across your operations.</p></div><button class="primary" id="addAssetBtn">＋ Add Asset</button></section>
<section class="cards"><div class="card"><label>Total Assets</label><strong id="total"></strong></div><div class="card"><label>Active</label><strong id="active"></strong></div><div class="card"><label>Due for Service</label><strong id="serviceDue"></strong></div><div class="card"><label>Open Defects</label><strong id="openDefects"></strong></div></section>
<div class="toolbar"><input id="search" placeholder="Search assets..."><select id="typeFilter"><option value="">All Asset Types</option>${assetTypes.map(x=>`<option>${x}</option>`).join('')}</select></div>
<section class="panel"><div class="tablewrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Registration</th><th>Plant ID</th><th>Odometer</th><th>Status</th><th>Actions</th></tr></thead><tbody id="rows"></tbody></table></div></section>
<div class="modal" id="assetModal"><div class="box"><div class="modalhead"><h2 id="modalTitle">Add Asset</h2><button class="close" data-close="assetModal">×</button></div><div class="viewerbody"><div class="grid">
<div class="field"><label>Asset Type *</label><select id="fType">${assetTypes.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Registration Number *</label><input id="fRego"></div>
<div class="field"><label>Registration State</label><select id="fRegistrationState"><option value="">Select Registration State</option>${stateOptions}</select></div><div class="field"><label>Registration Expiry Date</label><input id="fRegistrationExpiry" type="date"></div>
<div class="field"><label>Asset Status *</label><select id="fStatus">${statusOptions}</select></div><div class="field"><label>Make *</label><input id="fMake" list="makeList" placeholder="Select / enter make..."><datalist id="makeList"><option>Kenworth</option><option>Volvo</option><option>Mack</option><option>Mercedes-Benz</option><option>Isuzu</option><option>Hino</option><option>CAT</option><option>Komatsu</option><option>Toyota</option><option>Ford</option><option>MaxiTRANS</option></datalist></div>
<div class="field"><label>Model *</label><input id="fModel" placeholder="Model"></div><div class="field"><label>VIN</label><input id="fVin"></div>
<div class="field"><label>Current Odometer Reading *</label><input id="fReading" type="number" min="0"></div><div class="field"><label>Acquisition Date (Optional)</label><input id="fAcquisitionDate" type="date"></div>
<div class="field"><label>Category (Optional)</label><input id="fCategory"></div><div class="field"><label>Refrigeration Last Inspection Date (Optional)</label><input id="fRefrigerationInspectionDate" type="date"></div>
<label class="toggle"><input type="checkbox" id="fHandbrakeAlarm"> Handbrake Alarm</label><label class="toggle"><input type="checkbox" id="fReverseCamera"> Reverse Camera</label>
<label class="toggle"><input type="checkbox" id="fAdasVideo"> ADAS 4-Way Video</label><div class="field"><label>Insurance Expiry (Optional)</label><input id="fInsuranceExpiry" type="date"></div>
<div class="field"><label>Compliance Plate Date (Optional)</label><input id="fCompliancePlateDate" type="date"></div><div class="field"><label>Certificate of Inspection Number (Optional)</label><input id="fCoiNumber"></div>
<div class="field"><label>Certificate of Inspection Due Date (Optional)</label><input id="fCoiDueDate" type="date"></div><div class="field"><label>Asset ID or Plant ID (Optional)</label><input id="fPlantId"></div>
<div class="field"><label>Location</label><input id="fLocation"></div><label class="toggle"><input type="checkbox" id="fServiceDue"> Due for Service</label>
<div class="field full"><label>Additional Notes</label><textarea id="fAdditionalNotes" rows="4"></textarea></div>
</div></div><div class="actions"><button class="secondary" data-close="assetModal">Cancel</button><button class="primary" id="saveAsset">Save Asset</button></div></div></div>
<div class="modal" id="viewModal"><div class="box"><div class="modalhead"><h2>Asset Details</h2><button class="close" data-close="viewModal">×</button></div><div class="viewerbody" id="viewBody"></div><div class="actions"><button class="secondary" data-close="viewModal">Close</button><button class="primary" id="editFromView">Edit Asset</button></div></div></div>
<script>(()=>{const $=id=>document.getElementById(id);let list=[],editingId=null,viewingId=null;const fields=['Type','Rego','RegistrationState','RegistrationExpiry','Status','Make','Model','Vin','Reading','AcquisitionDate','Category','RefrigerationInspectionDate','InsuranceExpiry','CompliancePlateDate','CoiNumber','CoiDueDate','PlantId','Location','AdditionalNotes'];
async function load(){list=await fetch('/api/assets').then(r=>r.json());const s=await fetch('/api/asset-summary').then(r=>r.json());$('total').textContent=s.total;$('active').textContent=s.active;$('serviceDue').textContent=s.serviceDue;$('openDefects').textContent=s.openDefects;render()}
function render(){const q=$('search').value.toLowerCase(),t=$('typeFilter').value;$('rows').innerHTML=list.filter(a=>(!t||a.type===t)&&(!q||[a.name,a.type,a.rego,a.plantId,a.vin].join(' ').toLowerCase().includes(q))).map(a=>'<tr><td><b>'+a.name+'</b><div class="sub">'+(a.category||'')+'</div></td><td>'+a.type+'</td><td>'+a.rego+'<div class="sub">'+(a.registrationState||'')+'</div></td><td>'+(a.plantId||'—')+'</td><td>'+Number(a.reading||0).toLocaleString('en-AU')+'</td><td><span class="pill '+(a.status==='In Service'?'ok':'due')+'">'+a.status+'</span></td><td><div class="actionlinks"><button class="mini" data-view="'+a.id+'">View</button><button class="mini" data-edit="'+a.id+'">Edit</button></div></td></tr>').join('');$('rows').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewAsset(b.dataset.view));$('rows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function reset(){editingId=null;$('modalTitle').textContent='Add Asset';fields.forEach(n=>{const e=$('f'+n);if(e)e.value=''});$('fType').value=assetTypes[0];$('fStatus').value='In Service';['HandbrakeAlarm','ReverseCamera','AdasVideo','ServiceDue'].forEach(n=>$('f'+n).checked=false)}
function fill(a){$('fType').value=a.type||'';$('fRego').value=a.rego||'';$('fRegistrationState').value=a.registrationState||'';$('fRegistrationExpiry').value=a.registrationExpiry||'';$('fStatus').value=a.status||'In Service';$('fMake').value=a.make||'';$('fModel').value=a.model||'';$('fVin').value=a.vin||'';$('fReading').value=a.reading??'';$('fAcquisitionDate').value=a.acquisitionDate||'';$('fCategory').value=a.category||'';$('fRefrigerationInspectionDate').value=a.refrigerationInspectionDate||'';$('fHandbrakeAlarm').checked=!!a.handbrakeAlarm;$('fReverseCamera').checked=!!a.reverseCamera;$('fAdasVideo').checked=!!a.adasVideo;$('fInsuranceExpiry').value=a.insuranceExpiry||'';$('fCompliancePlateDate').value=a.compliancePlateDate||'';$('fCoiNumber').value=a.coiNumber||'';$('fCoiDueDate').value=a.coiDueDate||'';$('fPlantId').value=a.plantId||'';$('fLocation').value=a.location||'';$('fServiceDue').checked=!!a.serviceDue;$('fAdditionalNotes').value=a.additionalNotes||''}
function openEdit(id){const a=list.find(x=>x.id===id);if(!a)return;editingId=id;$('modalTitle').textContent='Edit Asset';fill(a);$('assetModal').classList.add('open')}
function viewAsset(id){const a=list.find(x=>x.id===id);if(!a)return;viewingId=id;const d=(label,v)=>'<div class="detail"><small>'+label+'</small><b>'+(v||'—')+'</b></div>';$('viewBody').innerHTML='<div class="detailgrid">'+d('Asset',a.name)+d('Asset Type',a.type)+d('Registration',a.rego)+d('Registration State',a.registrationState)+d('Registration Expiry',a.registrationExpiry)+d('Status',a.status)+d('Make',a.make)+d('Model',a.model)+d('VIN',a.vin)+d('Current Odometer',Number(a.reading||0).toLocaleString('en-AU'))+d('Acquisition Date',a.acquisitionDate)+d('Category',a.category)+d('Refrigeration Inspection',a.refrigerationInspectionDate)+d('Handbrake Alarm',a.handbrakeAlarm?'Yes':'No')+d('Reverse Camera',a.reverseCamera?'Yes':'No')+d('ADAS 4-Way Video',a.adasVideo?'Yes':'No')+d('Insurance Expiry',a.insuranceExpiry)+d('Compliance Plate Date',a.compliancePlateDate)+d('COI Number',a.coiNumber)+d('COI Due Date',a.coiDueDate)+d('Asset / Plant ID',a.plantId)+d('Location',a.location)+'</div><h3>Additional Notes</h3><p>'+(a.additionalNotes||'—')+'</p>';$('viewModal').classList.add('open')}
$('addAssetBtn').onclick=()=>{reset();$('assetModal').classList.add('open')};$('editFromView').onclick=()=>{$('viewModal').classList.remove('open');openEdit(viewingId)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$((b.dataset.close)).classList.remove('open'));$('search').oninput=render;$('typeFilter').onchange=render;
$('saveAsset').onclick=async()=>{const body={type:$('fType').value,rego:$('fRego').value,registrationState:$('fRegistrationState').value,registrationExpiry:$('fRegistrationExpiry').value,status:$('fStatus').value,make:$('fMake').value,model:$('fModel').value,vin:$('fVin').value,reading:$('fReading').value,acquisitionDate:$('fAcquisitionDate').value,category:$('fCategory').value,refrigerationInspectionDate:$('fRefrigerationInspectionDate').value,handbrakeAlarm:$('fHandbrakeAlarm').checked,reverseCamera:$('fReverseCamera').checked,adasVideo:$('fAdasVideo').checked,insuranceExpiry:$('fInsuranceExpiry').value,compliancePlateDate:$('fCompliancePlateDate').value,coiNumber:$('fCoiNumber').value,coiDueDate:$('fCoiDueDate').value,plantId:$('fPlantId').value,location:$('fLocation').value,serviceDue:$('fServiceDue').checked,additionalNotes:$('fAdditionalNotes').value};const r=await fetch(editingId?'/api/assets/'+editingId:'/api/assets',{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error||'Unable to save asset');$('assetModal').classList.remove('open');await load()};load()})();</script>`)));
module.exports=router;
