const express=require('express');
const router=express.Router();
const {page}=require('../layout');
const {assets}=require('../store');

const WIALON_HOST='https://hst-api.wialon.com';
let gpsConfig={token:'',connectedUser:'',lastTest:null,googleMapsKey:process.env.GOOGLE_MAPS_API_KEY||''};
const addressCache=new Map();

async function wialonCall(svc,params={},sid=''){
  const body=new URLSearchParams({svc,params:JSON.stringify(params)});if(sid)body.set('sid',sid);
  const r=await fetch(WIALON_HOST+'/wialon/ajax.html',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});
  const data=await r.json();if(data&&data.error)throw new Error('Wialon error '+data.error);return data;
}
async function login(){if(!gpsConfig.token)throw new Error('Wialon token has not been configured');return wialonCall('token/login',{token:gpsConfig.token});}
async function units(){const auth=await login();const data=await wialonCall('core/search_items',{spec:{itemsType:'avl_unit',propName:'sys_name',propValueMask:'*',sortType:'sys_name'},force:1,flags:1+256+1024,count:0,from:0,to:0},auth.eid);return (data.items||[]).map(u=>({id:String(u.id),name:u.nm,position:u.pos?{lat:u.pos.y,lon:u.pos.x,speed:u.pos.s||0,course:u.pos.c||0,time:u.pos.t||0}:null}));}

router.post('/api/gps/wialon/token',async(req,res)=>{try{const token=String(req.body?.token||'').trim();if(!token)return res.status(400).json({error:'Enter a Wialon token'});const old=gpsConfig.token;gpsConfig.token=token;try{const a=await login();gpsConfig.connectedUser=a.user?.nm||'';gpsConfig.lastTest=new Date().toISOString();res.json({ok:true,user:gpsConfig.connectedUser})}catch(e){gpsConfig.token=old;throw e}}catch(e){res.status(400).json({error:e.message})}});
router.post('/api/gps/google-key',(req,res)=>{const key=String(req.body?.key||'').trim();if(!key)return res.status(400).json({error:'Enter a Google Maps API key'});gpsConfig.googleMapsKey=key;res.json({ok:true})});
router.get('/api/gps/wialon/status',(req,res)=>res.json({configured:!!gpsConfig.token,user:gpsConfig.connectedUser,lastTest:gpsConfig.lastTest,googleMapsConfigured:!!gpsConfig.googleMapsKey}));
router.get('/api/gps/wialon/units',async(req,res)=>{try{res.json(await units())}catch(e){res.status(400).json({error:e.message})}});
router.post('/api/gps/link',(req,res)=>{const a=assets.find(x=>x.id===req.body?.assetId);if(!a)return res.status(404).json({error:'Asset not found'});a.wialonUnitId=String(req.body?.wialonUnitId||'');a.wialonUnitName=String(req.body?.wialonUnitName||'');res.json(a)});
router.get('/api/gps/live',async(req,res)=>{try{const us=await units();const byId=new Map(us.map(u=>[u.id,u]));res.json(assets.filter(a=>a.wialonUnitId).map(a=>({assetId:a.id,name:a.name,rego:a.rego,type:a.type,unit:byId.get(String(a.wialonUnitId))||null}))) }catch(e){res.status(400).json({error:e.message})}});
router.get('/api/gps/address',async(req,res)=>{try{if(!gpsConfig.googleMapsKey)return res.status(400).json({error:'Google Maps API key is not configured'});const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'Invalid coordinates'});const cacheKey=lat.toFixed(4)+','+lon.toFixed(4);if(addressCache.has(cacheKey))return res.json({address:addressCache.get(cacheKey),cached:true});const url='https://maps.googleapis.com/maps/api/geocode/json?latlng='+encodeURIComponent(lat+','+lon)+'&key='+encodeURIComponent(gpsConfig.googleMapsKey);const r=await fetch(url);const data=await r.json();if(data.status!=='OK'&&!data.results?.length)throw new Error('Unable to resolve address');const address=data.results?.[0]?.formatted_address||lat.toFixed(6)+', '+lon.toFixed(6);addressCache.set(cacheKey,address);if(addressCache.size>500)addressCache.delete(addressCache.keys().next().value);res.json({address})}catch(e){res.status(400).json({error:e.message})}});

router.get('/gps-integration',(req,res)=>res.send(page('settings','GPS Integration',`
<div class="title"><div><h1>GPS Integration</h1><p>Connect Supervisor365 to Wialon and Google Maps, then link tracking units to your assets.</p></div><a class="primary" href="/gps">Open Live GPS</a></div>
<section class="panel" style="padding:22px"><h2 style="margin-top:0">Wialon Connection</h2><p class="sub">The Wialon token stays on the Supervisor365 server and is not placed into the live map browser code.</p><div class="field" style="max-width:680px"><label>Wialon API Token</label><input id="token" type="password" autocomplete="off" placeholder="Paste Wialon token"></div><div style="display:flex;gap:8px;margin-top:12px"><button class="primary" id="connect">Save & Test Connection</button><span id="status" class="sub" style="align-self:center"></span></div></section>
<section class="panel" style="padding:22px"><h2 style="margin-top:0">Google Maps</h2><p class="sub">Required for the interactive road map and live marker hover cards. Restrict this key to your Supervisor365 domain in Google Cloud.</p><div class="field" style="max-width:680px"><label>Google Maps JavaScript API Key</label><input id="googleKey" type="password" autocomplete="off" placeholder="Paste Google Maps API key"></div><div style="display:flex;gap:8px;margin-top:12px"><button class="primary" id="saveGoogle">Save Google Maps Key</button><span id="googleStatus" class="sub" style="align-self:center"></span></div></section>
<section class="panel" style="padding:22px"><div class="sectionhead" style="margin:0 0 12px"><h2 style="margin:0">Asset ↔ Wialon Unit Linking</h2><button class="secondary" id="refresh">Refresh Units</button></div><div class="tablewrap"><table><thead><tr><th>Supervisor365 Asset</th><th>Registration</th><th>Wialon Unit</th><th>Action</th></tr></thead><tbody id="links"></tbody></table></div></section>
<script>(()=>{const assets=${JSON.stringify(assets).replace(/</g,'\\u003c')};let units=[];const $=id=>document.getElementById(id);async function status(){const s=await fetch('/api/gps/wialon/status').then(r=>r.json());$('status').textContent=s.configured?'Connected'+(s.user?' as '+s.user:''):'Not connected';$('googleStatus').textContent=s.googleMapsConfigured?'Google Maps configured':'Not configured'}async function load(){const r=await fetch('/api/gps/wialon/units');const d=await r.json();if(!r.ok){$('links').innerHTML='<tr><td colspan="4"><div class="empty">'+(d.error||'Connect Wialon first')+'</div></td></tr>';return}units=d;render()}function render(){$('links').innerHTML=assets.map(a=>'<tr><td><b>'+a.name+'</b><div class="sub">'+a.type+'</div></td><td>'+a.rego+'</td><td><select id="u_'+a.id+'"><option value="">Not linked</option>'+units.map(u=>'<option value="'+u.id+'" '+(String(a.wialonUnitId||'')===u.id?'selected':'')+'>'+u.name+'</option>').join('')+'</select></td><td><button class="mini" data-save="'+a.id+'">Save Link</button></td></tr>').join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const a=assets.find(x=>x.id===b.dataset.save),sel=$('u_'+a.id),u=units.find(x=>x.id===sel.value);const r=await fetch('/api/gps/link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetId:a.id,wialonUnitId:sel.value,wialonUnitName:u?.name||''})});if(r.ok){a.wialonUnitId=sel.value;b.textContent='Saved ✓';setTimeout(()=>b.textContent='Save Link',1200)}})}$('connect').onclick=async()=>{const token=$('token').value.trim();if(!token)return alert('Paste your Wialon token first.');$('connect').disabled=true;$('connect').textContent='Testing...';const r=await fetch('/api/gps/wialon/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json();$('connect').disabled=false;$('connect').textContent='Save & Test Connection';if(!r.ok)return alert(d.error||'Connection failed');$('token').value='';await status();await load()};$('saveGoogle').onclick=async()=>{const key=$('googleKey').value.trim();if(!key)return alert('Paste your Google Maps API key first.');const r=await fetch('/api/gps/google-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});const d=await r.json();if(!r.ok)return alert(d.error||'Unable to save key');$('googleKey').value='';await status();alert('Google Maps key saved. Reload Live GPS to use the interactive map.')};$('refresh').onclick=load;status();load()})();</script>`)));

router.get('/gps',(req,res)=>{const mapsKey=gpsConfig.googleMapsKey;res.send(page('dashboard','Live GPS',`
<style>
.gpsShell{display:grid;grid-template-columns:300px 1fr;gap:14px;height:calc(100vh - 155px);min-height:590px}.gpsSide{background:#fff;border:1px solid #e3e8ef;border-radius:12px;display:flex;flex-direction:column;overflow:hidden}.gpsSideHead{padding:15px;border-bottom:1px solid #edf1f5}.gpsSideHead h3{margin:0 0 4px}.unitList{overflow:auto;flex:1}.gpsUnit{display:grid;grid-template-columns:26px 1fr 18px;gap:9px;align-items:center;padding:12px 14px;border-bottom:1px solid #edf1f5;cursor:pointer}.gpsUnit:hover,.gpsUnit.focused{background:#f5f9ff}.gpsUnit input{width:18px;height:18px;accent-color:#2577e3}.liveDot{width:10px;height:10px;border-radius:50%;background:#21a35b;box-shadow:0 0 0 4px #21a35b22}.liveDot.moving{animation:pulse 1.5s infinite}.mapWrap{position:relative;border:1px solid #e3e8ef;border-radius:12px;overflow:hidden;background:#e8edf3}.googleMap{width:100%;height:100%}.mapNotice{height:100%;display:grid;place-items:center;padding:30px;text-align:center;color:#65758a}.trackBadge{position:absolute;z-index:2;top:14px;left:14px;background:#101827ef;color:#fff;border-radius:10px;padding:9px 12px;font-size:12px;box-shadow:0 5px 18px #0002;display:none}.trackBadge.on{display:block}.trackBadge .pulse{display:inline-block;width:8px;height:8px;border-radius:50%;background:#31d47d;margin-right:7px;animation:pulse 1.4s infinite}.hoverCard{min-width:250px;max-width:310px;padding:4px}.hoverTitle{display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:15px;font-weight:800;margin-bottom:8px}.hoverStatus{width:9px;height:9px;border-radius:50%;background:#21a35b;display:inline-block;margin-left:6px}.hoverAddress{font-size:12px;line-height:1.45;color:#536174;margin:8px 0 10px}.hoverStats{display:grid;grid-template-columns:1fr 1fr;gap:6px}.hoverStat{background:#f6f8fb;border-radius:7px;padding:8px;font-size:11px}.hoverStat b{display:block;color:#172033;font-size:14px;margin-top:2px}@keyframes pulse{0%{box-shadow:0 0 0 0 #31d47d77}70%{box-shadow:0 0 0 8px #31d47d00}100%{box-shadow:0 0 0 0 #31d47d00}}@media(max-width:800px){.gpsShell{grid-template-columns:1fr;height:auto}.gpsSide{max-height:280px}.mapWrap{height:65vh;min-height:430px}}
</style>
<div class="title"><div><h1>Live GPS</h1><p>Hover over any vehicle marker for its live address, speed and latest GPS update.</p></div><a class="secondary" href="/gps-integration">GPS Integration</a></div>
<div class="gpsShell"><aside class="gpsSide"><div class="gpsSideHead"><h3>Tracked Assets</h3><div class="sub"><label style="display:flex;gap:8px;align-items:center"><input id="allUnits" type="checkbox" checked> Show all linked units</label></div></div><div id="gpsList" class="unitList"><div class="empty">Loading live positions...</div></div></aside><div class="mapWrap"><div id="trackBadge" class="trackBadge"><span class="pulse"></span><span id="trackText">Live tracking</span></div><div id="map" class="googleMap">${mapsKey?'':'<div class="mapNotice"><div><b>Google Maps is not configured yet.</b><br><br>Open GPS Integration and add your Google Maps API key to enable the interactive road map and marker hover details.</div></div>'}</div></div></div>
${mapsKey?`<script src="https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(mapsKey)}&v=weekly"></script>`:''}
<script>(()=>{
let rows=[],visible=new Set(),followId='',firstLoad=true,map=null,markers=new Map(),info=null,addressByAsset=new Map();const list=document.getElementById('gpsList'),all=document.getElementById('allUnits'),badge=document.getElementById('trackBadge'),trackText=document.getElementById('trackText');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function initMap(){if(!window.google||!google.maps)return;map=new google.maps.Map(document.getElementById('map'),{center:{lat:-27.47,lng:153.03},zoom:10,mapTypeId:'roadmap',streetViewControl:false,mapTypeControl:true,fullscreenControl:true});info=new google.maps.InfoWindow()}
function selectedRows(){return rows.filter(x=>visible.has(x.assetId))}
function markerIcon(row){const moving=Number(row.unit.position.speed)>1;return {path:google.maps.SymbolPath.CIRCLE,scale:9,fillColor:moving?'#1fa55b':'#2c77d8',fillOpacity:1,strokeColor:'#fff',strokeWeight:3}}
async function resolveAddress(row){if(addressByAsset.has(row.assetId))return addressByAsset.get(row.assetId);const p=row.unit.position;try{const r=await fetch('/api/gps/address?lat='+encodeURIComponent(p.lat)+'&lon='+encodeURIComponent(p.lon));const d=await r.json();const address=r.ok?d.address:(p.lat.toFixed(5)+', '+p.lon.toFixed(5));addressByAsset.set(row.assetId,address);return address}catch{return p.lat.toFixed(5)+', '+p.lon.toFixed(5)}}
async function showInfo(row,marker){const p=row.unit.position;const initial='<div class="hoverCard"><div class="hoverTitle"><span>'+esc(row.name)+'<span class="hoverStatus"></span></span><span style="font-size:11px;color:#7c8898">'+(p.time?esc(new Date(p.time*1000).toLocaleTimeString('en-AU')):'—')+'</span></div><div class="hoverAddress">Finding current address…</div><div class="hoverStats"><div class="hoverStat">Speed<b>'+Math.round(p.speed)+' km/h</b></div><div class="hoverStat">Registration<b>'+esc(row.rego)+'</b></div></div></div>';info.setContent(initial);info.open({map,anchor:marker});const address=await resolveAddress(row);if(!info.getMap())return;info.setContent('<div class="hoverCard"><div class="hoverTitle"><span>'+esc(row.name)+'<span class="hoverStatus"></span></span><span style="font-size:11px;color:#7c8898">'+(p.time?esc(new Date(p.time*1000).toLocaleTimeString('en-AU')):'—')+'</span></div><div class="hoverAddress">'+esc(address)+'</div><div class="hoverStats"><div class="hoverStat">Speed<b>'+Math.round(p.speed)+' km/h</b></div><div class="hoverStat">Registration<b>'+esc(row.rego)+'</b></div></div></div>')}
function syncMarkers(){if(!map)return;const current=new Set();for(const row of rows){if(!visible.has(row.assetId))continue;current.add(row.assetId);const p=row.unit.position;let marker=markers.get(row.assetId);if(!marker){marker=new google.maps.Marker({map,position:{lat:p.lat,lng:p.lon},title:row.name,icon:markerIcon(row)});marker.addListener('mouseover',()=>{const live=rows.find(x=>x.assetId===row.assetId)||row;showInfo(live,marker)});marker.addListener('mouseout',()=>{if(info)info.close()});marker.addListener('click',()=>{followId=row.assetId;render();updateViewport(true)});markers.set(row.assetId,marker)}else{marker.setMap(map);marker.setPosition({lat:p.lat,lng:p.lon});marker.setIcon(markerIcon(row))}}
for(const [id,m] of markers){if(!current.has(id)){m.setMap(null);markers.delete(id)}}}
function render(){if(!rows.length){list.innerHTML='<div class="empty">No linked assets with a current Wialon position.<br><br><a href="/gps-integration">Link assets</a></div>';return}list.innerHTML=rows.map(x=>{const p=x.unit.position,moving=Number(p.speed)>1;return '<label class="gpsUnit '+(followId===x.assetId?'focused':'')+'"><input type="checkbox" data-show="'+x.assetId+'" '+(visible.has(x.assetId)?'checked':'')+'><div data-focus="'+x.assetId+'"><b>'+esc(x.name)+'</b><div class="sub">'+esc(x.rego)+' · '+Math.round(p.speed)+' km/h</div><div class="sub">'+(p.time?new Date(p.time*1000).toLocaleTimeString('en-AU'):'No GPS time')+'</div></div><span class="liveDot '+(moving?'moving':'')+'"></span></label>'}).join('');list.querySelectorAll('[data-show]').forEach(cb=>cb.onchange=e=>{e.stopPropagation();if(cb.checked)visible.add(cb.dataset.show);else{visible.delete(cb.dataset.show);if(followId===cb.dataset.show)followId=''}all.checked=visible.size===rows.length;syncMarkers();updateViewport()});list.querySelectorAll('[data-focus]').forEach(el=>el.onclick=e=>{e.preventDefault();const id=el.dataset.focus;if(!visible.has(id))visible.add(id);followId=id;render();syncMarkers();updateViewport(true)})}
function updateViewport(force=false){if(!map)return;const chosen=selectedRows();if(followId){const x=rows.find(r=>r.assetId===followId&&visible.has(r.assetId));if(x){const p=x.unit.position;trackText.textContent=x.name+' · '+Math.round(p.speed)+' km/h';badge.classList.add('on');map.panTo({lat:p.lat,lng:p.lon});if(force||map.getZoom()<15)map.setZoom(17);return}}badge.classList.remove('on');if(!chosen.length)return;if(chosen.length===1){const p=chosen[0].unit.position;map.panTo({lat:p.lat,lng:p.lon});if(force)map.setZoom(16);return}if(force||firstLoad){const bounds=new google.maps.LatLngBounds();chosen.forEach(x=>bounds.extend({lat:x.unit.position.lat,lng:x.unit.position.lon}));map.fitBounds(bounds,70)}}
async function refresh(){const r=await fetch('/api/gps/live'),d=await r.json();if(!r.ok){list.innerHTML='<div class="empty">'+(d.error||'Unable to load GPS')+'<br><br><a href="/gps-integration">Configure Wialon</a></div>';return}rows=d.filter(x=>x.unit&&x.unit.position);if(firstLoad){rows.forEach(x=>visible.add(x.assetId))}const valid=new Set(rows.map(x=>x.assetId));[...visible].forEach(id=>{if(!valid.has(id))visible.delete(id)});if(followId&&!valid.has(followId))followId='';render();syncMarkers();updateViewport(firstLoad);firstLoad=false}
all.onchange=()=>{visible.clear();if(all.checked)rows.forEach(x=>visible.add(x.assetId));if(!all.checked)followId='';render();syncMarkers();updateViewport(true)};initMap();refresh();setInterval(refresh,5000)
})();</script>`))});
module.exports=router;
