const nodemailer=require('nodemailer');
const clean=v=>String(v??'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function configured(){return !!(clean(process.env.SMTP_HOST)&&clean(process.env.SMTP_USER)&&clean(process.env.SMTP_PASS))}
function transport(){if(!configured())return null;return nodemailer.createTransport({host:clean(process.env.SMTP_HOST),port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'').toLowerCase()==='true',auth:{user:clean(process.env.SMTP_USER),pass:String(process.env.SMTP_PASS||'')}})}
function baseUrl(){return clean(process.env.APP_PUBLIC_URL)||'https://marksupervisor.onrender.com'}
async function send(to,subject,html){const t=transport();if(!t)return{sent:false,code:'SMTP_NOT_CONFIGURED'};const info=await t.sendMail({from:clean(process.env.MAIL_FROM)||'Supervisor365 <no-reply@supervisor365.com.au>',to,subject,html});return{sent:true,messageId:info.messageId}}
async function sendCompanyReady(company,user){return send(user.email,'Your Supervisor365 company account is ready',`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#172433"><h2>Welcome to Supervisor365</h2><p>Your company workspace for <b>${esc(company.name)}</b> has been created.</p><p><b>Username:</b> ${esc(user.username)}</p><p><a href="${esc(baseUrl())}/login" style="display:inline-block;background:#1679c4;color:#fff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700">Sign in to Supervisor365</a></p><p style="font-size:12px;color:#687789">For security, your password is never included in email.</p></div>`)}
async function sendEmployeeWelcome(company,user,tempPassword){return send(user.email,`${company.name} has created your Supervisor365 account`,`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#172433"><h2>Your Supervisor365 account</h2><p>${esc(company.name)} has created an account for you.</p><p><b>Username:</b> ${esc(user.username)}<br><b>Temporary password:</b> ${esc(tempPassword)}</p><p>You will be required to change this temporary password after signing in.</p><p><a href="${esc(baseUrl())}/login" style="display:inline-block;background:#1679c4;color:#fff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700">Sign in</a></p></div>`)}
module.exports={configured,send,sendCompanyReady,sendEmployeeWelcome,baseUrl};