const express=require('express');
if(!express.response.__sv365SmartNavFixPatched){
  express.response.__sv365SmartNavFixPatched=true;
  const originalSend=express.response.send;
  const assist=String.raw`<style id="svSmartNavAssistStyle">.smartMobileClose{display:none}@media(max-width:800px){.smartMobileClose{display:grid;place-items:center;margin-left:auto;width:34px;height:34px;border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.04);color:#dce5ef;border-radius:9px;cursor:pointer;flex:0 0 34px}.smartMobileClose svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round}}</style><script id="svSmartNavAssist">(()=>{setTimeout(()=>{const side=document.getElementById('svSidebar'),head=side&&side.querySelector('.smartHead');if(head&&!head.querySelector('.smartMobileClose')){const b=document.createElement('button');b.type='button';b.className='smartMobileClose';b.setAttribute('aria-label','Close navigation');b.innerHTML='<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>';b.onclick=()=>side.classList.remove('mobileOpen');head.appendChild(b)}const top=document.getElementById('svTop'),title=document.getElementById('navContextTitle'),hint=document.getElementById('navContextHint'),eyebrow=document.getElementById('navEyebrow'),current=title?title.textContent:'';function show(label){if(!title)return;title.textContent=label;if(hint)hint.textContent='Click to open this section';if(eyebrow)eyebrow.textContent='Navigation preview';if(top)top.classList.add('preview')}function restore(){if(!title)return;title.textContent=current;if(hint)hint.textContent='Supervisor365 operations workspace';if(eyebrow)eyebrow.textContent='Current section';if(top)top.classList.remove('preview')}document.querySelectorAll('.smartChild[data-nav-label],.smartHome[data-nav-label]').forEach(a=>{a.addEventListener('mouseenter',()=>show(a.dataset.navLabel));a.addEventListener('mouseleave',restore);a.addEventListener('focus',()=>show(a.dataset.navLabel));a.addEventListener('blur',restore)});document.querySelectorAll('.smartGroupButton').forEach(b=>{const label=b.querySelector('.smartNavLabel')?.textContent;if(!label)return;b.addEventListener('mouseenter',()=>show(label));b.addEventListener('mouseleave',restore)})},0)})();</script>`;
  express.response.send=function(body){
    if(typeof body==='string'&&body.includes('svSmartNavV1')){
      body=body.replace("+(path==='/assets'||path==='/')?'active':''+'","+((path==='/assets'||path==='/')?'active':'')+");
      if(!body.includes('svSmartNavAssist')&&body.includes('</body>'))body=body.replace('</body>',assist+'</body>');
    }
    return originalSend.call(this,body);
  };
}
